### ISSUE TITLE
where ? translation...

### ISSUE THREAD

**Issue by ghost** [BurgerZ/WSM-Project#1]
hey there, where i can upload the FR translation for wsm.manager ?
i dont' see it in your repos

i uploaded strings.xml here : http://pastebin.com/k6w86tZb

**Comment by BurgerZ** [comment]
Thanks. I'll make WSM resources folder in wsm repo.

**Comment by BurgerZ** [comment]
Please, retranslate. I have uploaded the latest values/strings.xml

**Comment by ghost** [comment]
Ok, and about modules strings ? :)

**Comment by BurgerZ** [comment]
@cpasmoi OK. I can share resources of modules, but I have in plans make all modules open source.
