### ISSUE TITLE
Need @mention on pre-release update.

### ISSUE THREAD

**Issue by RadarNyan** [BurgerZ/WSM-Project#27]
Every time WSM-Tools or any Module updates, I don't get any notification. If the update contains any new values and I don't update my translation in time (without a notification, it happens a lot), then new release will only contain my old translation which will make it incomplete. I barely make this update for Mi-Tools 1.2 (Did I just made it in time? I'm still not very sure...) 

So, is it possible for us(translators) to get a notification before a new version being released? Maybe you can just send us @mentions on updates need new translation, so we can update translations in time.

Thanks in advance :)

RadarNyan

**Comment by RadarNyan** [comment]
@BurgerZ 
Well... Just updated to 1.2, apparently I didn't make the commit in time.

**Comment by BurgerZ** [comment]
@RadarNyan OK, I'll wait until you update your translations. I could send emails for all translators. No problems.

**Comment by RadarNyan** [comment]
@BurgerZ Sorry for missing for the last two updates, had some problem with my laptop and connection problem with github (I still have to use a proxy to get here right now x_x) I'm late but still updated translation, and I'll be follow up from next update.

I tried "Show the date with the status bar clock" option in module Mi-Tools, it comes up with something like "28 11月, 01:42" which is not correct format in Chinese (the correct format would be "11月28日 01:42") would you like to make it possible to localize in the future release?

And for localization Units, by "kb", "mb"... what exactly does they mean? Let's take "kb" as example. If it means kilobyte, then it should be "KB", if kibibyte, then "KiB" and (not very likely) kilobit should be "kb". It may not mean very much to end-users, I'm just trying to be as accurate as possible. (I think I'm kind of OCD...)

**Comment by BurgerZ** [comment]
Kb etc. changed to normal KB... Thanks.
Mi-Tools will be updated every friday (like MIUI) at about 8:00 - 9:00 GMT so you can just edit translations before release.
