### ISSUE TITLE
Request for supporting MIUIPolska.pl MMS Festival database

### ISSUE THREAD

**Issue by zdunex25** [BurgerZ/WSM-Project#29]
Here it goes: https://github.com/Acid-miuipolskapl/XML_MIUI-v5/blob/6c1d31b9c08fea62d2700362ae5d37ecf21a9ab4/Polish/main/Mms.apk/res/raw-pl/festival_sms.db

**Comment by BurgerZ** [comment]
Do you have an online festival database for PL? Not db file, but URL with json.
