### ISSUE TITLE
How to add SK and CZ Holidays to the module.?

### ISSUE THREAD

**Issue by ingbrzy** [BurgerZ/WSM-Project#4]
Hi... how can I add SK and CZ holidays to the calendar and alarm module..?

**Comment by BurgerZ** [comment]
Hi. Just give me your info and update server (if any):
Original http://api.comm.miui.com/holiday/holiday.jsp
Russian romz http://cloud.romz.bz/holidays/
Where workday is numbers of working (sundays and saturdays) days in year, freeday - that is free days from monday to friday.

**Comment by ingbrzy** [comment]
Slovak Republic holidays for 2013
http://calendar.miui.cz/holidays-sk.jsp

Czech Republic
http://calendar.miui.cz/holidays-cz.jsp

**Comment by BurgerZ** [comment]
@ingbrzy tomorrow I'll publish resources and update module with your servers.

**Comment by ingbrzy** [comment]
thank you..!

**Comment by vagyula1** [comment]
Hungarian holidays for 2014
http://miuiandroid.hu/holidays-hu.jsp
