### ISSUE TITLE
MI3 bootloop

### ISSUE THREAD

**Issue by zdunex25** [BurgerZ/WSM-Project#45]
WSM makes MI 3W loop, I do not have logcat cause it was a friend of mine that reported such behavior. I will try to get logcat, but wanted to let you know anyway.

**Comment by BurgerZ** [comment]
I know about this issue, but I have no logs from users who have reported bootloops. That is the main problem in solving issues. But I hope that in 2.1.8 there will be no bootloops.

**Comment by vagyula1** [comment]
How to help you?
Where i find the log file?Because still get bootloop.

**Comment by zdunex25** [comment]
You should connect your Mi3W to PC, open terminal then type adb logcat >> log.txt and the next step would be sharing log.txt with us.

**Comment by vagyula1** [comment]
https://www.dropbox.com/s/aghmrrnd3wswzc5/log.txt
Is it okay for you?

**Comment by zdunex25** [comment]
Log is good, now we should wait to see whether @BurgerZ will be able to find a cause.

**Comment by BurgerZ** [comment]
oh.... The log is no good (log is good, but things in it are not), I'll try to find ut the reason, but.. I'll have mi3 soon, so I'll fix it anyway))) I want to use WSM on all my Android-based phones.

**Comment by vagyula1** [comment]
Any news?:-)

**Comment by miuirussia** [comment]
In new MIUI v5/v6 firmwares there is protection (or fitch) from programs like WSM/Xposed. It's called DexSpy and works the same (patching original method without changing method), but without opened API.

**Comment by BurgerZ** [comment]
@miuirussia Oh. Yeah, that's the reason of bootloop! android.policy and services jars has methods that pointed to dexspy, app_process from that miui versions has dexspy classloader, but xposed app_process has no, so jvm failes while loading frameworks. 
I can try to avoid bootloops.

**Comment by MIUIwolfpapa** [comment]
Please solve it ...THX!
Please help Xiaomi Mi3 community.
XDA/Xposed:
" here is one stack trace:
E/AndroidRuntime( 7078):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:568)
E/AndroidRuntime( 7078):        at miui.dexspy.DexspyInstaller.main(DexspyInstaller.java:170)
E/AndroidRuntime( 7078):        at dalvik.system.NativeStart.main(Native Method) "

"Well I would have to say that it is, at least it looks like it from logs like this
https://github.com/KDGDev/miui-v5-russian-translation-for-miuiandroid/issues/24
Code:
at miui.dexspy.DexspyInstaller.invokeOriginalMethodNative(Native Method)
at miui.dexspy.DexspyInstaller.invokeOriginalMethod(DexspyInstaller.java:490)
at miui.dexspy.DexspyInstaller.handleHookedMethod(DexspyInstaller.java:404)
This seams very familiar.

 But would this not be overwritten if you install Xposed? I mean there can only be one binary. "

**Comment by MIUIwolfpapa** [comment]
http://en.miui.com/thread-16609-1-2.html

**Comment by zdunex25** [comment]
@miuirussia @BurgerZ is this going to help you guys: https://github.com/MiCode/dexspy ?

**Comment by BurgerZ** [comment]
@zdunex25 I hope. I'm trying to build new app_process for mi3w now.

**Comment by zdunex25** [comment]
Fingers crossed @BurgerZ

**Comment by vagyula1** [comment]
v2.2.3 works fine on my Mi3W.
@BurgerZ: Many thanks :)

**Comment by BurgerZ** [comment]
Updated to v2.2.4. Fixed some stuff to improve boot time on our device (Mi3W) and fix some FCs. Reinstall binaries manually.

**Comment by zdunex25** [comment]
Well done :) thank you.

**Comment by MIUIwolfpapa** [comment]
Thank You!
