### ISSUE TITLE
error with XposedBridgeApi42.jar

### ISSUE THREAD

**Issue by seveniruby** [BurgerZ/WSM-Project#49]
i use XposedBridgeApi42.jar on my phone 
xposed tell me error with 

```
04-05 22:18:11.770      118-118/? W/dalvikvm﹕ Class resolved by unexpected DEX: Lcom/testerhome/mobileagent/app/Hook;(0x40f83cc0):0x40c20000 ref [Lde/robv/android/xposed/IXposedHookLoadPackage;] Lde/robv/android/xposed/IXposedHookLoadPackage;(0x40d86db0):0x400ac000
04-05 22:18:11.770      118-118/? W/dalvikvm﹕ (Lcom/testerhome/mobileagent/app/Hook; had used a different Lde/robv/android/xposed/IXposedHookLoadPackage; during pre-verification)

```

i found the wsm tools on my phone show with xposedbridge.jar 46
does the XposedBridgeApi42.jar out of date? or can you update the jar file?

my phone is miui 4.2.28 + android 4.2.2

**Comment by BurgerZ** [comment]
Did you use XposedBridgeApi42.jar to build your module? Or this error occures in my modules?

**Comment by seveniruby** [comment]
i use it in my module

**Comment by seveniruby** [comment]
i use appsetting module of the xposed, that work well.
so  i think it maybe my fault, maybe i package the  xposedbridge.jar into the modules.
i would review my code.  sorry for the trouble
