### ISSUE TITLE
Which is the default language of WSM-Project?

### ISSUE THREAD

**Issue by nuomi1** [BurgerZ/WSM-Project#50]
I am going to translate simplified Chinese, but I can't find which is the default language.
For example in https://github.com/BurgerZ/WSM-Project/tree/master/WSM%20tools/res , "raw" describes "v2.1.2 upd" and "values" describes "Update translations", but the latest version is 2.2.4.
I think it needs to write the current version in the XML.

**Comment by zdunex25** [comment]
Translate raw and values, @BurgerZ is going to update today or tomorrow with missing strings from latest version.

**Comment by BurgerZ** [comment]
@nuomi1 default English as always, my main language is Russian. I'll update translations in xml in a few hours.
