### ISSUE TITLE
Long time no see the developer update the translation file

### ISSUE THREAD

**Issue by ghost** [BurgerZ/WSM-Project#52]
I was finished the Traditional Chinese(Taiwan) translation file long time,But I have not seen the developer @BurgerZ  update the new translation strings into the new version of WSM ToolBox........

So,can the developer @BurgerZ  update the new translation strings into the next WSM ToolBox update???

**Comment by BurgerZ** [comment]
WSM Tools translation update regularly https://github.com/BurgerZ/WSM-Project/commits/master/WSM%20tools/res/values
There was a time I had no time for development.

**Comment by ghost** [comment]
OK,I know, that can you update the WSM ToolBox with Traditional Chinese translation in the next time??

Thanks you~~

**Comment by BurgerZ** [comment]
What is "WSM ToolBox"? I've updated local translations, next update will include all your new strings.
