### ISSUE TITLE
Need to update the Tr.Chinese translation file in  WSM ToolBox and Mi Tool

### ISSUE THREAD

**Issue by ghost** [BurgerZ/WSM-Project#53]
I was sync theTr.Chinese translation and fix some bad translation to the WSM ToolBox  and Mi Tool latest version!!

So... Can @BurgerZ  update the WSM ToolBox with new Tr.Chinese translation file ??

Thanks you

**Comment by BurgerZ** [comment]
Please, do not open issues for translations!
