### ISSUE TITLE
Remove icon or add option to hide icon of "Mi-Tools" on launcher

### ISSUE THREAD

**Issue by daviduuang** [BurgerZ/WSM-Project#55]
As we all know, instead of having the app drawer, all your apps are laid out across a number of homescreens on MIUI ROM. So we should take full use of every space of icon. 

Currently, As a module, "Mi-Tools" have a separated icon on homescreen. Also, we can access its settings from "WSM tools" directly(as the picture shows below). 

![mi_20140510_101018](https://cloud.githubusercontent.com/assets/5523894/2935009/02d6d634-d7eb-11e3-8c62-28600e994fda.png)

I think almost no one will install a single "Mi-tools" without "WSM tools" installed. So I think a separated icon for "Mi-Tools" on homescreen is not so necessary. Maybe, you can provide "Hide Mi-tools icon" as an option.

**Comment by zdunex25** [comment]
There is a possibility to hide any icon in mitools, so just hide the icon.

**Comment by daviduuang** [comment]
Never found a possibility to hide icons in Mi-Tools. I just find "Hide icons labels" option(Do you mean it?). 

Mi-Tools V2.0.3
![mi_20140510_183915](https://cloud.githubusercontent.com/assets/5523894/2935834/ccb61854-d82f-11e3-8cfb-07d15a0f1580.png)

**Comment by zdunex25** [comment]
Go to Main Page > Launcher > very bottom - Hide app icons.

**Comment by daviduuang** [comment]
I couldn't find any options about "Hide app icons" at bottom.

![mi_20140510_192335](https://cloud.githubusercontent.com/assets/5523894/2935923/b55f8512-d836-11e3-806a-7fef75e2eba6.png)

I asked someone who use Mi-Tools, they couldn't find it, too.
Could you give a clear explain about it, Please? 
Thx.

**Comment by zdunex25** [comment]
If no such option exists then wait for update 2.0.4 I forgot that I was testing beta releases with new features.

**Comment by BurgerZ** [comment]
Yes. Hide app icons option will be available in 2.0.4, @zdunex25 has the test build with this option, so @imfirefly you have to just wait for v2.0.4 to be released.
