### ISSUE TITLE
plurals for modules_count ?

### ISSUE THREAD

**Issue by ghost** [BurgerZ/WSM-Project#59]
hello, it's possible to you add plurals.xml for 
`<string name="modules_count">Modules: %1$d | Active: %2$d</string>` ?

in my language it's displayed as 
`<string name="modules_count">Module(s) : %1$d | Actif(s) : %2$d</string>`

those `(s)` are ugly !... 

if possible to add plurals for **0**, **1** and **others**. but i believe that some languages (cz/sk)have multiples plurals..

thanks you :+1:

**Comment by zdunex25** [comment]
You can adjust it (look) in your translation.

**Comment by BurgerZ** [comment]
@cpasmoi OK, I'll add plurals. But you can use universal way, like:

```
Modules: %1$d | Active : %2$d
```

So Modules can be 0,1,2,100))

**Comment by ghost** [comment]
Ok i modified my translation.
but "Modules" can't be 0 and 1, "Active" can be only 0 and 1, at least in french..

**Comment by BurgerZ** [comment]
```
but "Modules" can't be 0 and 1, "Active" can be only 0 and 1, at least in french..
```

Modules can be 0, 1, 100, 29345875 in any language, I think. It's just like Modules = "Modules count: 1" and Active = Active modules. But anyway I'll do what you asked.
