### ISSUE TITLE
МиТемес доделать нада

### ISSUE THREAD

**Issue by finist1** [BurgerZ/WSM-Project#64]
Хай ду ду.
framework2.jar/miui/drm/DrmBroadcast.smali
Убираю метод:
.method public broadcast()V
    .locals 8
    .prologue
    .line 28
    return-void
.end method

На сг Ноте 3 прокатывает. На сг 4 вроде тоже :yum:

**Comment by BurgerZ** [comment]
Все, что касается этого модуля, пишите на почту. 
Будет время, может поковыряю. Может через пару недель.
А здесь буду удалять))
