### ISSUE TITLE
MiThemes caused random reboot on MIUI 6

### ISSUE THREAD

**Issue by What-Zit-Tooya** [BurgerZ/WSM-Project#67]
Hi.
I'm using MIUI 6 and my device always reboot if i use paid themes.
My device normal If i use paid Themes & theme authorization, but revert back to default theme in several hours.
Can you solve that problem?

**Comment by zdunex25** [comment]
This module is not supporting miui v6, @BurgerZ released sources you can update yourself.

**Comment by What-Zit-Tooya** [comment]
Where is the source & how to build?

**Comment by zdunex25** [comment]
SRC: https://github.com/BurgerZ/WSM-Project/commit/0f93a6ce9c395d687ded64b82bac55c459ab8b16

ABOUT: https://github.com/rovo89/XposedBridge/wiki/Development-tutorial

**Comment by What-Zit-Tooya** [comment]
That is source for mithemes on miui 5, can i use that source to miui 6?

**Comment by BurgerZ** [comment]
You can do with this sourse code whatever you want, but it wont work on miui v6) You have to change it to make it work on v6.
