### ISSUE TITLE
mithemes is broken on new / latest miui 5

### ISSUE THREAD

**Issue by Arsyadi** [BurgerZ/WSM-Project#68]
I'm using redmi note 3g & using latest miui v5 rom  global version here http://enbigota.d.miui.com/JHDMIBL40.0/miui_H3WGlobal_JHDMIBL40.0_4f833c1539_4.2.zip
My device always reboot . Already deleted jex file but still not working.

**Comment by BurgerZ** [comment]
I do not update MiThemes - this module violates licences. I've released source code so you can do it yourself.
