### ISSUE TITLE
WSM tools 2.3.5 broken in 5.9.23 MIUI 7 china dev. rom

### ISSUE THREAD

**Issue by What-Zit-Tooya** [BurgerZ/WSM-Project#71]
I get this error message when try to install framework 

<a href='http://postimage.org/' target='_blank'><img src='http://s24.postimg.org/f1633ds2t/WSM_Error.jpg' border='0' alt="WSM Error" /></a><br /><a target='_blank' href='http://postimage.org/app.php'>greenshot</a><br /><br />

**Comment by zdunex25** [comment]
Means you are not allowed to use wsm anymore, at least no without updating.

**Comment by What-Zit-Tooya** [comment]
So, wsm not compatible to latest miui rom?

**Comment by zdunex25** [comment]
If it's kitkat based miui v7 then use Xposed installer from official source it supports miui.

**Comment by BurgerZ** [comment]
Current WSM version is not compatible with MIUI v7.
